### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by Vaibhavdixit02**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I rebased BTW.

**Comment by Vaibhavdixit02** [comment]
Shit, I missed that

**Comment by ChrisRackauckas** [comment]
I'll force over yours, and then let you finish it.

**Comment by Vaibhavdixit02** [comment]
Thanks! Sorry about that

**Comment by ChrisRackauckas** [comment]
You take it from here. I just jolted it into the standard form for all of our new docs. I am not sure if it all runs but it should be close.

**Comment by Vaibhavdixit02** [comment]
Great 👍

**Comment by ChrisRackauckas** [comment]
BTW, we should show AutoForwardDiff here since Zygote does not make sense on a small model like this. To showcase the Zygote choice, there should be another tutorial that's focused on a larger model.

**Comment by ChrisRackauckas** [comment]
Okay cool, a lot of it worked. Can you fix up that last bit? Then we should do a quick merge so the majority of it is in.

**Pull request merged**
